### ISSUE TITLE
server not booting with 1.7.10-1.5.0-48

### ISSUE THREAD

**Issue by TheMrCaveman** [MineMaarten/PneumaticCraft#336]
---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 12/26/14 5:31 PM
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/client/multiplayer/WorldClient
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:515)
    at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/multiplayer/WorldClient
    at pneumaticCraft.common.item.Itemss.init(Itemss.java:81)
    at pneumaticCraft.PneumaticCraft.PreInit(PneumaticCraft.java:77)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
    ... 5 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.multiplayer.WorldClient
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 33 more
Caused by: java.lang.RuntimeException: Attempted to load class bjf for invalid side SERVER
    at cpw.mods.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:50)
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
    ... 35 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Linux (amd64) version 2.6.32-042stab075.2
    Java Version: 1.8.0_05, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 23684888 bytes (22 MB) / 257224704 bytes (245 MB) up to 8072527872 bytes (7698 MB)
    JVM Flags: 9 total; -Xms32M -Xmx7964M -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:+CMSClassUnloadingEnabled -XX:ParallelGCThreads=5 -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:MaxMetaspaceSize=512M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.85.1277 Minecraft Forge 10.13.2.1277 37 mods loaded, 37 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized
    FML{7.10.85.1277} [Forge Mod Loader](forge-1.7.10-10.13.2.1277-universal.jar) Unloaded->Constructed->Pre-initialized
    Forge{10.13.2.1277} [Minecraft Forge](forge-1.7.10-10.13.2.1277-universal.jar) Unloaded->Constructed->Pre-initialized
    CodeChickenCore{1.0.4.29} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized
    NotEnoughItems{1.0.4.80} [Not Enough Items](NotEnoughItems-1.7.10-1.0.4.80-universal.jar) Unloaded->Constructed->Pre-initialized
    OpenComputers|Core{1.0.0} [OpenComputers (Core)](minecraft.jar) Unloaded->Constructed->Pre-initialized
    OpenEye{0.6} [OpenEye](OpenEye-0.6-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    backpacks16840{3.0.1} [Backpacks!](zz-backpacks 1.7.10 - 3.0.2.jar) Unloaded->Constructed->Pre-initialized
    ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships](ArchimedesShips-1.7.1.jar) Unloaded->Constructed->Pre-initialized
    Backpack{2.0.1} [Backpack](backpack-2.0.1-1.7.x.jar) Unloaded->Constructed->Pre-initialized
    BiblioCraft{1.9.1} [BiblioCraft](BiblioCraft[v1.9.1][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized
    BiomesOPlenty{2.1.0} [Biomes O' Plenty](BiomesOPlenty-1.7.10-2.1.0.1034-universal.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Core{6.2.6} [BuildCraft](buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Transport{6.2.6} [BC Transport](buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Silicon{6.2.6} [BC Silicon](buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Builders{6.2.6} [BC Builders](buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Energy{6.2.6} [BC Energy](buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Factory{6.2.6} [BC Factory](buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized
    eureka{2.2} [Eureka](Eureka-1.7.10-2.2.jar) Unloaded->Constructed->Pre-initialized
    bcadditions{1.8.3} [Buildcraft Additions](BuildcraftAdditions-1.7.10-1.8.3.jar) Unloaded->Constructed->Pre-initialized
    CarpentersBlocks{3.3.4} [Carpenter's Blocks](Carpenter's Blocks v3.3.4 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized
    ChickenChunks{1.3.4.16} [ChickenChunks](ChickenChunks-1.7.10-1.3.4.16-universal.jar) Unloaded->Constructed->Pre-initialized
    Dynmap{2.0.0-61} [Dynmap](Dynmap-2.0.0-forge-10.13.0.jar) Unloaded->Constructed->Pre-initialized
    Forestry{3.3.0.6} [Forestry for Minecraft](forestry_1.7.10-3.3.0.6.jar) Unloaded->Constructed->Pre-initialized
    inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks](InventoryTweaks-1.59-dev-152.jar) Unloaded->Constructed->Pre-initialized
    IronChest{6.0.62.742} [Iron Chest](ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded->Constructed->Pre-initialized
    JABBA{1.2.0a} [JABBA](Jabba-1.2.0a_1.7.10.jar) Unloaded->Constructed->Pre-initialized
    cfm{3.4.7} [�9MrCrayfish's Furniture Mod](MrCrayfishFurnitureModv3.4.7%281.7.10%29.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons{1.12.3.11} [NEI Addons](neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons|Botany{1.12.3.11} [NEI Addons: Botany](neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons|Forestry{1.12.3.11} [NEI Addons: Forestry](neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons|CraftingTables{1.12.3.11} [NEI Addons: Crafting Tables](neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons|ExNihilo{1.12.3.11} [NEI Addons: Ex Nihilo](neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized
    OpenComputers{1.4.2.16} [OpenComputers](OpenComputers-MC1.7.10-1.4.2.16-universal.jar) Unloaded->Constructed->Pre-initialized
    PneumaticCraft{1.5.0-48} [PneumaticCraft](PneumaticCraft-1.7.10-1.5.0-48-universal.jar) Unloaded->Constructed->Errored
    Railcraft{9.4.0.0} [Railcraft](Railcraft_1.7.10-9.4.0.0.jar) Unloaded->Constructed->Pre-initialized
    TwilightForest{2.3.2} [The Twilight Forest](twilightforest-1.7.10-2.3.2.jar) Unloaded->Constructed->Pre-initialized
    Profiler Position: N/A (disabled)
    Is Modded: Definitely; Server brand changed to 'fml,forge'
    Type: Dedicated Server (map_server.txt)

**Comment by CatDany** [comment]
You don't even know how happy I am right now. I found a fix for my problem. Thanks, Maarten! :O
