### ISSUE TITLE
Crash Report with cc (2 different crashes)

### ISSUE THREAD

**Issue by lieven121** [MineMaarten/PneumaticCraft#338]
crash 1 when using the program 

---- Minecraft Crash Report ----
// My bad.

Time: 26/12/14 20:53
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at pneumaticCraft.common.util.PneumaticCraftUtils.isEntityValidForFilterUnsafe(PneumaticCraftUtils.java:514)
	at pneumaticCraft.common.util.PneumaticCraftUtils.isEntityValidForFilter(PneumaticCraftUtils.java:507)
	at pneumaticCraft.common.ai.StringFilterEntitySelector.func_82704_a(StringFilterEntitySelector.java:19)
	at pneumaticCraft.common.progwidgets.ProgWidgetAreaItemBase.getEntitiesInArea(ProgWidgetAreaItemBase.java:133)
	at pneumaticCraft.common.thirdparty.computercraft.ProgWidgetCC.getValidEntities(ProgWidgetCC.java:221)
	at pneumaticCraft.common.ai.DroneAINearestAttackableTarget.func_75250_a(DroneAINearestAttackableTarget.java:40)
	at pneumaticCraft.common.thirdparty.computercraft.DroneAICC.func_75250_a(DroneAICC.java:53)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:70)
	at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:537)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1772)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1609)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
	at pneumaticCraft.common.entity.living.EntityDrone.func_70071_h_(EntityDrone.java:289)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at WorldServerOF.func_72870_g(WorldServerOF.java:394)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at pneumaticCraft.common.util.PneumaticCraftUtils.isEntityValidForFilterUnsafe(PneumaticCraftUtils.java:514)
	at pneumaticCraft.common.util.PneumaticCraftUtils.isEntityValidForFilter(PneumaticCraftUtils.java:507)
	at pneumaticCraft.common.ai.StringFilterEntitySelector.func_82704_a(StringFilterEntitySelector.java:19)
	at pneumaticCraft.common.progwidgets.ProgWidgetAreaItemBase.getEntitiesInArea(ProgWidgetAreaItemBase.java:133)
	at pneumaticCraft.common.thirdparty.computercraft.ProgWidgetCC.getValidEntities(ProgWidgetCC.java:221)
	at pneumaticCraft.common.ai.DroneAINearestAttackableTarget.func_75250_a(DroneAINearestAttackableTarget.java:40)
	at pneumaticCraft.common.thirdparty.computercraft.DroneAICC.func_75250_a(DroneAICC.java:53)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:70)
	at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:537)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1772)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1609)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
	at pneumaticCraft.common.entity.living.EntityDrone.func_70071_h_(EntityDrone.java:289)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at WorldServerOF.func_72870_g(WorldServerOF.java:394)

-- Entity being ticked --
Details:
	Entity Type: PneumaticCraft.Drone (pneumaticCraft.common.entity.living.EntityDrone)
	Entity ID: 2879
	Entity Name: Drone
	Entity's Exact location: -476,50, 40,50, -59,50
	Entity's Block location: World: (-477,40,-60), Chunk: (at 3,2,4 in -30,-4; contains blocks -480,0,-64 to -465,255,-49), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0,00, 0,00, 0,00
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: program
	All players: 1 total; [EntityPlayerMP['lieven121'/142, l='program', x=-477,24, y=40,00, z=-61,67]]
	Chunk stats: ServerChunkCache: 291 Drop: 0
	Level seed: -8143139369817903861
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 2;;1;village
	Level spawn location: World: (-485,4,-61), Chunk: (at 11,0,3 in -31,-4; contains blocks -496,0,-64 to -481,255,-49), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 231382 game time, 257205 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 37629 (now: false), thunder time: 18859 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.7.0_67, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 225557920 bytes (215 MB) / 643260416 bytes (613 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1232 Minecraft Forge 10.13.2.1232 Optifine OptiFine_1.7.10_HD_U_A4 28 mods loaded, 28 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1232} [Forge Mod Loader] (forge-1.7.10-10.13.2.1232.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1232} [Minecraft Forge] (forge-1.7.10-10.13.2.1232.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	appliedenergistics2-core{rv1-stable-1} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	LanteaCraft-Core{1.0} [LanteaCraft Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NotEnoughItems{1.0.3.62} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.62-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OpenModsCore{0.6} [OpenModsCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	appliedenergistics2{rv1-stable-1} [Applied Energistics 2] (appliedenergistics2-rv1-stable-1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ComputerCraft{1.65} [ComputerCraft] (ComputerCraft1.65.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMultipart{1.1.0.314} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ExtraUtilities{1.2.0} [Extra Utilities] (extrautilities-1.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	McMultipart{1.1.0.314} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	IC2{2.2.657-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.657-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	IC2NuclearControl{2.0.0b} [Nuclear Control 2] (IC2NuclearControl-2.0.0b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	LanteaCraft{1.0.0-63} [LanteaCraft] (LanteaCraft-1.7.10-63.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mantle{1.7.10-0.3.1.jenkins180} [Mantle] (Mantle-mc1.7.10-0.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OpenMods{0.6} [OpenMods] (OpenModsLib-1.7.10-0.6-snapshot-268.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Thaumcraft{4.2.2.1} [Thaumcraft] (Thaumcraft-1.7.10-4.2.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OpenPeripheralCore{0.5.0} [OpenPeripheralCore] (OpenPeripheralCore-1.7.10-0.5.0-snapshot-172.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OpenPeripheral{0.2.0} [OpenPeripheralAddons] (OpenPeripheralAddons-1.7.10-0.2.0-snapshot-139.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OpenBlocks{1.3} [OpenBlocks] (OpenBlocks-1.7.10-1.3-snapshot-513.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OpenPeripheralIntegration{0.1.0} [OpenPeripheralIntegration] (OpenPeripheralIntegration-1.7.10-0.1.0-snapshot-17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	PneumaticCraft{1.5.0-48} [PneumaticCraft] (PneumaticCraft-1.7.10-1.5.0-48-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TConstruct{1.7.10-1.6.0.build611} [Tinkers' Construct] (TConstruct_mc1.7.10_1.6.0d40.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMicroblock{1.1.0.314} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OpenModsLib crash transformers: [gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED],[map_gen_fix:FINISHED],[movement_callback:FINISHED],[stencil_patches:FINISHED]
	AE2 Version: stable rv1-stable-1 for Forge 10.13.0.1187
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	TConstruct Environment: Environment healthy.
	Stencil buffer state: Function set: ARB, pool: internal, bits: 8
	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:OFF, BC:OFF, MJ6:OFF, MJ5:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:OFF, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:OFF, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['lieven121'/142, l='program', x=-477,24, y=40,00, z=-61,67]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

crash 2 when trying to load the world while the program is in autorun (startup)

---- Minecraft Crash Report ----
// You're mean.

Time: 26/12/14 20:50
Description: Rendering screen

java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.network.NetworkManager
	at net.minecraft.client.Minecraft.func_71371_a(Minecraft.java:2126)
	at cpw.mods.fml.client.FMLClientHandler.tryLoadExistingWorld(FMLClientHandler.java:669)
	at net.minecraft.client.gui.GuiSelectWorld.func_146615_e(GuiSelectWorld.java:183)
	at net.minecraft.client.gui.GuiSelectWorld$List.func_148144_a(GuiSelectWorld.java:257)
	at net.minecraft.client.gui.GuiSlot.func_148128_a(GuiSlot.java:209)
	at net.minecraft.client.gui.GuiSelectWorld.func_73863_a(GuiSelectWorld.java:216)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1352)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.Minecraft.func_71371_a(Minecraft.java:2126)
	at cpw.mods.fml.client.FMLClientHandler.tryLoadExistingWorld(FMLClientHandler.java:669)
	at net.minecraft.client.gui.GuiSelectWorld.func_146615_e(GuiSelectWorld.java:183)
	at net.minecraft.client.gui.GuiSelectWorld$List.func_148144_a(GuiSelectWorld.java:257)
	at net.minecraft.client.gui.GuiSlot.func_148128_a(GuiSlot.java:209)
	at net.minecraft.client.gui.GuiSelectWorld.func_73863_a(GuiSelectWorld.java:216)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.GuiMainMenu
	Mouse location: Scaled: (202, 59). Absolute: (599, 610)
	Screen size: Scaled: (456, 256). Absolute: (1366, 768). Scale factor of 3
Stacktrace:
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1352)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.7.0_67, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 316522648 bytes (301 MB) / 632766464 bytes (603 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1232 Minecraft Forge 10.13.2.1232 Optifine OptiFine_1.7.10_HD_U_A4 28 mods loaded, 28 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1232} [Forge Mod Loader] (forge-1.7.10-10.13.2.1232.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1232} [Minecraft Forge] (forge-1.7.10-10.13.2.1232.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	appliedenergistics2-core{rv1-stable-1} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	LanteaCraft-Core{1.0} [LanteaCraft Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NotEnoughItems{1.0.3.62} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.62-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OpenModsCore{0.6} [OpenModsCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	appliedenergistics2{rv1-stable-1} [Applied Energistics 2] (appliedenergistics2-rv1-stable-1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ComputerCraft{1.65} [ComputerCraft] (ComputerCraft1.65.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMultipart{1.1.0.314} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ExtraUtilities{1.2.0} [Extra Utilities] (extrautilities-1.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	McMultipart{1.1.0.314} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	IC2{2.2.657-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.657-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	IC2NuclearControl{2.0.0b} [Nuclear Control 2] (IC2NuclearControl-2.0.0b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	LanteaCraft{1.0.0-63} [LanteaCraft] (LanteaCraft-1.7.10-63.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mantle{1.7.10-0.3.1.jenkins180} [Mantle] (Mantle-mc1.7.10-0.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OpenMods{0.6} [OpenMods] (OpenModsLib-1.7.10-0.6-snapshot-268.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Thaumcraft{4.2.2.1} [Thaumcraft] (Thaumcraft-1.7.10-4.2.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OpenPeripheralCore{0.5.0} [OpenPeripheralCore] (OpenPeripheralCore-1.7.10-0.5.0-snapshot-172.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OpenPeripheral{0.2.0} [OpenPeripheralAddons] (OpenPeripheralAddons-1.7.10-0.2.0-snapshot-139.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OpenBlocks{1.3} [OpenBlocks] (OpenBlocks-1.7.10-1.3-snapshot-513.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OpenPeripheralIntegration{0.1.0} [OpenPeripheralIntegration] (OpenPeripheralIntegration-1.7.10-0.1.0-snapshot-17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	PneumaticCraft{1.5.0-48} [PneumaticCraft] (PneumaticCraft-1.7.10-1.5.0-48-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TConstruct{1.7.10-1.6.0.build611} [Tinkers' Construct] (TConstruct_mc1.7.10_1.6.0d40.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMicroblock{1.1.0.314} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OpenModsLib crash transformers: [gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED],[map_gen_fix:FINISHED],[movement_callback:FINISHED],[stencil_patches:FINISHED]
	AE2 Version: stable rv1-stable-1 for Forge 10.13.0.1187
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	TConstruct Environment: Environment healthy.
	Stencil buffer state: Function set: ARB, pool: internal, bits: 8
	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:OFF, BC:OFF, MJ6:OFF, MJ5:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:OFF, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:OFF, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Launched Version: 1.7.10-Forge10.13.2.1232
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics GL version 2.1.0 - Build 8.15.10.2622, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by MineMaarten** [comment]
afaik this would only happen when you're doing 'peripheral.addWhitelistText(nil)'. But it's fixed in next version. The second crash is vague, but could be some kind of side effect of this.
