### ISSUE TITLE
java.lang.ClassCastException: pneumaticCraft.common.progwidgets.ProgWidgetDroneConditionItem

### ISSUE THREAD

**Issue by Protheus** [MineMaarten/PneumaticCraft#398]
From the server (SMP) crash log see below (http://pastebin.com/V6Fp5rwy)

The server keeps rebooting

PneumaticCraft-1.7.10-1.5.5-58-universal
Forge: 1286

Description: Ticking entity
 
java.lang.ClassCastException: pneumaticCraft.common.progwidgets.ProgWidgetDroneConditionItem cannot be cast to pneumaticCraft.common.progwidgets.ProgWidgetAreaItemBase
        at pneumaticCraft.common.progwidgets.ProgWidgetDroneConditionItem.getCount(ProgWidgetDroneConditionItem.java:26)
        at pneumaticCraft.common.progwidgets.ProgWidgetDroneEvaluation.evaluate(ProgWidgetDroneEvaluation.java:75)
        at pneumaticCraft.common.progwidgets.ProgWidgetDroneEvaluation.getOutputWidget(ProgWidgetDroneEvaluation.java:70)
        at pneumaticCraft.common.ai.DroneAIManager.setActiveWidget(DroneAIManager.java:83)
        at pneumaticCraft.common.ai.DroneAIManager.updateWidgetFlow(DroneAIManager.java:54)
        at pneumaticCraft.common.ai.DroneAIManager.onUpdateTasks(DroneAIManager.java:176)
        at pneumaticCraft.common.entity.living.EntityDrone.func_70071_h_(EntityDrone.java:292)
        at net.minecraft.world.World.func_72866_a(World.java:2070)
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
        at net.minecraft.world.World.func_72870_g(World.java:2034)
        at net.minecraft.world.World.func_72939_s(World.java:1887)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by Protheus** [comment]
edit: PneumaticCraft-1.7.10-1.5.5-59-universal
