### ISSUE TITLE
Crash on Server (ClassNotFoundException: net.minecraft.client.multiplayer.WorldClient)

### ISSUE THREAD

**Issue by martinaovivo** [MineMaarten/PneumaticCraft#408]
Version:

PneumaticCraft-1.7.10-1.5.6-59

Log:

```
java.lang.NoClassDefFoundError: net/minecraft/client/multiplayer/WorldClient
	at net.minecraft.world.Explosion.func_77278_a(Explosion.java:139) ~[agw.class:?]
	at net.minecraft.world.WorldServer.func_72885_a(WorldServer.java:901) ~[mt.class:?]
	at net.minecraft.world.World.func_72876_a(World.java:2403) ~[ahb.class:?]
	at pneumaticCraft.common.EventHandlerPneumaticCraft.onEntityDeath(EventHandlerPneumaticCraft.java:129) ~[EventHandlerPneumaticCraft.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_416_EventHandlerPneumaticCraft_onEntityDeath_LivingDeathEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:303) [ForgeHooks.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:891) [sv.class:?]
	at net.minecraft.entity.monster.EntityCreeper.func_70645_a(SourceFile:134) [xz.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:855) [sv.class:?]
	at net.minecraft.entity.monster.EntityMob.func_70097_a(SourceFile:54) [yg.class:?]
	at net.minecraft.entity.monster.EntityMob.func_70652_k(SourceFile:101) [yg.class:?]
	at net.minecraft.entity.monster.EntityMob.func_70785_a(SourceFile:126) [yg.class:?]
	at net.minecraft.entity.EntityCreature.func_70626_be(SourceFile:63) [td.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1780) [sv.class:?]
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367) [sw.class:?]
	at net.minecraft.entity.monster.EntityMob.func_70636_d(SourceFile:25) [yg.class:?]
	at crazypants.enderzoo.entity.EntityEnderminy.func_70636_d(EntityEnderminy.java:231) [EntityEnderminy.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611) [sv.class:?]
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206) [sw.class:?]
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:30) [yg.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:2070) [ahb.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648) [mt.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:2034) [ahb.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1887) [ahb.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.multiplayer.WorldClient
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	... 32 more
```

Line 129 is:

```
if(Config.enableCreeperDropExplosion) event.entity.worldObj.createExplosion(event.entity, event.entity.posX, event.entity.posY + event.entityLiving.height / 2D, event.entity.posZ, 0.5F, event.entity.worldObj.getGameRules().getGameRuleBooleanValue("mobGriefing"));
```

Temporary  fix?

B:"Enable Creeper Explosions on seed drop"=false

**Comment by MineMaarten** [comment]
After a chat Neptunepink was pretty sure it was a (well hidden) Factorization bug. So either update to a newer version of Factorization or wait for a new version :P. Until then, the server also should crash when for example TNT explodes.

**Comment by martinaovivo** [comment]
Thank you very much. I am updating.
