### ISSUE TITLE
game crashes whan running drone program

### ISSUE THREAD

**Issue by Donrest** [MineMaarten/PneumaticCraft#446]
hi,

i have a problem my game crashes every time the drone picks me up on this program. it is a problem with the the [Drone Condition: Entity] puzzel peace. i have tried several different layouts. but all layouts with te DCE puzzel peace crashes my game whan i am pickt up by the drone. any suggestions on wat the problem can be or is it just a bug?
![image](https://cloud.githubusercontent.com/assets/11966947/7167426/2e9245d4-e3b5-11e4-9db0-96dd1ca6ec35.png)

(i whant to use this program later on a server to bring players to me and check if they jump off to pick them up agen)

**Comment by MineMaarten** [comment]
Crashes always have a crashlog, can I take a look at it?

**Comment by Donrest** [comment]
here is the crashreport.

---- Minecraft Crash Report ----
// Don't do that.

Time: 15-4-15 20:45
Description: Ticking entity

java.lang.ClassCastException: pneumaticCraft.common.progwidgets.ProgWidgetDroneConditionEntity cannot be cast to pneumaticCraft.common.progwidgets.ProgWidgetAreaItemBase
	at pneumaticCraft.common.progwidgets.ProgWidgetDroneConditionEntity.getCount(ProgWidgetDroneConditionEntity.java:25)
	at pneumaticCraft.common.progwidgets.ProgWidgetDroneEvaluation.evaluate(ProgWidgetDroneEvaluation.java:31)
	at pneumaticCraft.common.progwidgets.ProgWidgetConditionBase.getOutputWidget(ProgWidgetConditionBase.java:38)
	at pneumaticCraft.common.ai.DroneAIManager.setActiveWidget(DroneAIManager.java:163)
	at pneumaticCraft.common.ai.DroneAIManager.updateWidgetFlow(DroneAIManager.java:132)
	at pneumaticCraft.common.ai.DroneAIManager.onUpdateTasks(DroneAIManager.java:261)
	at pneumaticCraft.common.entity.living.EntityDrone.func_70071_h_(EntityDrone.java:296)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at pneumaticCraft.common.progwidgets.ProgWidgetDroneConditionEntity.getCount(ProgWidgetDroneConditionEntity.java:25)
	at pneumaticCraft.common.progwidgets.ProgWidgetDroneEvaluation.evaluate(ProgWidgetDroneEvaluation.java:31)
	at pneumaticCraft.common.progwidgets.ProgWidgetConditionBase.getOutputWidget(ProgWidgetConditionBase.java:38)
	at pneumaticCraft.common.ai.DroneAIManager.setActiveWidget(DroneAIManager.java:163)
	at pneumaticCraft.common.ai.DroneAIManager.updateWidgetFlow(DroneAIManager.java:132)
	at pneumaticCraft.common.ai.DroneAIManager.onUpdateTasks(DroneAIManager.java:261)
	at pneumaticCraft.common.entity.living.EntityDrone.func_70071_h_(EntityDrone.java:296)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
	Entity Type: PneumaticCraft.Drone (pneumaticCraft.common.entity.living.EntityDrone)
	Entity ID: 5306
	Entity Name: Drone
	Entity's Exact location: 220,00, 65,38, 229,00
	Entity's Block location: World: (220,65,229), Chunk: (at 12,4,5 in 13,14; contains blocks 208,0,224 to 223,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: -0,05, 0,00, -0,05
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['_Architect_'/157, l='New World', x=220,10, y=65,14, z=229,10]]
	Chunk stats: ServerChunkCache: 694 Drop: 0
	Level seed: 4227899286034777648
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (228,64,228), Chunk: (at 4,4,4 in 14,14; contains blocks 224,0,224 to 239,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 4232 game time, 4232 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 134212 (now: false), thunder time: 91899 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 148934264 bytes (142 MB) / 432791552 bytes (412 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.112.1373 Minecraft Forge 10.13.3.1373 5 mods loaded, 5 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.112.1373} [Forge Mod Loader] (forge-1.7.10-10.13.3.1373-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.3.1373} [Minecraft Forge] (forge-1.7.10-10.13.3.1373-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	IGWMod{1.1.1-14} [In-Game wiki Mod] (IGW-Mod-1.7.10-1.1.1-14-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	PneumaticCraft{1.6.6-68} [PneumaticCraft] (PneumaticCraft-1.7.10-1.6.6-68-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['_Architect_'/157, l='New World', x=220,10, y=65,14, z=229,10]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by MineMaarten** [comment]
tyvm! It's fixed in next version :)
