### ISSUE TITLE
Coordinate Tracker Navigation hangs client.

### ISSUE THREAD

**Issue by ruifung** [MineMaarten/PneumaticCraft#587]
Sometimes, the client would randomly hang and sometimes not respond at all.
So I decided to take a thread dump to see what was going on - turns out the pathfinding was being done from the client thread and when it doesn't stop.. it hangs the client.

In fact, in this case when it hang - it hangs every single time I rejoin the server.

Thread dump client thread during hang:
```
"Client thread" #1 prio=5 os_prio=0 tid=0x0000000002c9e800 nid=0x43f4 runnable [0x0000000002d9d000]
   java.lang.Thread.State: RUNNABLE
	at net.minecraft.pathfinding.PathFinderDrone.openPoint(PathFinderDrone.java:231)
	at net.minecraft.pathfinding.PathFinderDrone.getSafePoint(PathFinderDrone.java:221)
	at net.minecraft.pathfinding.PathFinderDrone.findPathOptions(PathFinderDrone.java:163)
	at net.minecraft.pathfinding.PathFinderDrone.addToPath(PathFinderDrone.java:122)
	at net.minecraft.pathfinding.PathFinderDrone.createEntityPathTo(PathFinderDrone.java:94)
	at net.minecraft.pathfinding.PathFinderDrone.createEntityPathTo(PathFinderDrone.java:66)
	at pneumaticCraft.common.ai.EntityPathNavigateDrone.getEntityPathToXYZ(EntityPathNavigateDrone.java:91)
	at pneumaticCraft.client.render.pneumaticArmor.CoordTrackUpgradeHandler.getDronePath(CoordTrackUpgradeHandler.java:180)
	at pneumaticCraft.client.render.pneumaticArmor.RenderNavigator.updatePath(RenderNavigator.java:34)
	at pneumaticCraft.client.render.pneumaticArmor.RenderNavigator.<init>(RenderNavigator.java:27)
	at pneumaticCraft.client.render.pneumaticArmor.CoordTrackUpgradeHandler.update(CoordTrackUpgradeHandler.java:81)
	at pneumaticCraft.client.render.pneumaticArmor.HUDHandler.update(HUDHandler.java:200)
	at pneumaticCraft.client.render.pneumaticArmor.HUDHandler.playerTick(HUDHandler.java:107)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_322_HUDHandler_playerTick_PlayerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:350)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:353)
	at net.minecraft.client.entity.EntityClientPlayerMP.func_70071_h_(SourceFile:63)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

```

**Comment by MineMaarten** [comment]
This doesn't suprise me. Pathfinding is the only thing that can really impact the Coordinate Tracker. Not entirely sure what I can do about it though (apart from limiting the times that the pathfinder is used, but that will still generate lagspikes when it does).. :(. It's failing pathfinding in particular which causes the lage.

**Comment by ruifung** [comment]
Not lag, client stalled completely. Either you can uh.. thread it? Or at least put a limit on the length of time it runs. Say if it runs longer then X and fails - stop pathfinding for a minute or 2, that way at least it doesn't hang the client - at least this was on a server and I could teleport myself out, if this was singleplayer I'd probably have to modify the player data file to get myself out.

**Comment by MineMaarten** [comment]
Well, pathfinding isn't thread safe. Also the putting a timeout on it is hard, as it's vanilla code.

**Comment by ruifung** [comment]
I think the main issue that causes this, is when it tries to pathfind to a very far point. I wonder what would happen if it tries to pathfind to beyond the render distance or view-distance by server.. ?

**Comment by MineMaarten** [comment]
it shouldn't try further than 300 blocks. But probably just decreasing that to 150 blocks will help in a major way (as increasing the max search distance is exponentional)
