### ISSUE TITLE
Crash with HeatBehavior (NullPointerException)

### ISSUE THREAD

**Issue by SanAndreasP** [MineMaarten/PneumaticCraft#689]
Minecraft: 1.7.10
Forge: 10.13.4.1492
Pneumaticcraft: 1.11.6-126

So, sometimes Minecraft just randomly crashes when I operate with heat (heating sth. up with Pyrotheum or cooling sth down with heat sinks + comp. iron blocks). It happened always when I was inside a machine GUI which shows its heat (plastic mixer, refinery and flux compressor).

This is the crash stacktrace:
```
java.lang.NullPointerException: Ticking screen
	at pneumaticCraft.api.tileentity.HeatBehaviour.getTileEntity(HeatBehaviour.java:61)
	at pneumaticCraft.common.heat.behaviour.HeatBehaviourFurnace.isApplicable(HeatBehaviourFurnace.java:16)
	at pneumaticCraft.common.heat.behaviour.HeatBehaviourManager.addHeatBehaviours(HeatBehaviourManager.java:59)
	at pneumaticCraft.common.heat.HeatExchangerLogic.initializeAsHull(HeatExchangerLogic.java:38)
	at pneumaticCraft.common.tileentity.TileEntityBase.initializeHeatExchanger(TileEntityBase.java:359)
	at pneumaticCraft.common.tileentity.TileEntityBase.initializeIfHeatExchanger(TileEntityBase.java:354)
	at pneumaticCraft.common.tileentity.TileEntityBase.onNeighborBlockUpdate(TileEntityBase.java:336)
	at pneumaticCraft.common.tileentity.TileEntityBase.redstoneAllows(TileEntityBase.java:340)
	at pneumaticCraft.common.tileentity.TileEntityPlasticMixer.redstoneAllows(TileEntityPlasticMixer.java:404)
	at pneumaticCraft.client.gui.GuiPneumaticContainerBase.addProblems(GuiPneumaticContainerBase.java:359)
	at pneumaticCraft.client.gui.GuiPlasticMixer.addProblems(GuiPlasticMixer.java:104)
	at pneumaticCraft.client.gui.GuiPneumaticContainerBase.func_73876_c(GuiPneumaticContainerBase.java:310)
	at pneumaticCraft.client.gui.GuiPlasticMixer.func_73876_c(GuiPlasticMixer.java:67)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1661)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

Here is the full log:
https://gist.github.com/SanAndreasP/964a05c469c2b85343db

**Comment by GirafiStudios** [comment]
There is no crash in that log tho.. :p

**Comment by pyure** [comment]
The NPE on the first line is the crash.

**Comment by SanAndreasP** [comment]
@GirafiStudios You need to view the full log (it's truncated), there's a link (warning: quite big log):
https://gist.githubusercontent.com/SanAndreasP/964a05c469c2b85343db/raw/2c8f94839e86b22c7393e4674d10d80a79afb99f/fml-client-latest.log
