### ISSUE TITLE
drone right click - World Edit interaction Error

### ISSUE THREAD

**Issue by dalgrim** [MineMaarten/PneumaticCraft#743]
I get this error when using a drone to plant crops using the right click puzzle piece

SEVERE: [WorldEdit] Could not dispatch event: com.sk89q.worldedit.event.platform.PlayerInputEvent@24921a69 to handler EventHandler{priority=NORMAL}
java.lang.reflect.InvocationTargetException
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:75)
        at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:187)
        at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:173)
        at com.sk89q.worldedit.WorldEdit.handleRightClick(WorldEdit.java:664)
        at com.sk89q.worldedit.forge.ForgeWorldEdit.onPlayerInteract(ForgeWorldEdit.java:178)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_775_ForgeWorldEdit_onPlayerInteract_PlayerInteractEvent.invoke(.dynamic)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
        at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:100)
        at pneumaticCraft.common.ai.DroneAIBlockInteract.rightClick(DroneAIBlockInteract.java:96)
        at pneumaticCraft.common.ai.DroneAIBlockInteract.doBlockInteraction(DroneAIBlockInteract.java:41)
        at pneumaticCraft.common.ai.DroneAIBlockInteraction.func_75253_b(DroneAIBlockInteraction.java:187)
        at pneumaticCraft.common.ai.DroneAIManager.onUpdateTasks(DroneAIManager.java:302)
        at pneumaticCraft.common.entity.living.EntityDrone.func_70071_h_(EntityDrone.java:315)
        at net.minecraft.world.World.func_72866_a(World.java:2070)
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
        at net.minecraft.world.World.func_72870_g(World.java:2034)
        at net.minecraft.world.World.func_72939_s(World.java:1887)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor78.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58)
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73)
        ... 23 more
Caused by: java.lang.NullPointerException

here is the pastebin link to the program I used:
http://pastebin.com/qtLHcbQX

-edit: I forgot I edited the program to take the conditional and  right click out of the flow so that the server wouldn't have the error... I did leave in the puzzle pieces though.

Server is a DW20 1.7.10 running recommended  version (1.7.0) I added Worldedit to the server though.

**Comment by MineMaarten** [comment]
Hmm looks like some weird interaction problem with WorldEdit...

**Comment by dalgrim** [comment]
That was my guess as well. I was able to isolate it to the right click. It was planting netherwarts into soulsand. The drone was working correctly but every time it would try to plant the server console would spam that error. I'm not sure if the problem is WorldEdit or the right click method of the drone So I'm making a report at both places.

**Comment by MineMaarten** [comment]
I'll await WorldEdit's response, as that's where the crash(log) happens.
