### ISSUE TITLE
NEI Recipe Crash

### ISSUE THREAD

**Issue by Joshi120** [MineMaarten/PneumaticCraft#750]
Hello :) i have a weird issue each time i try to look up a Recipe my game crashes with this 

java.lang.IllegalStateException: Looking up recipe for 1xtile.pressureTube@0: 100xfluid.lubricant(518){null}, despite being in the keyset of the map, returned null on get()!Map data: {pneumaticCraft.common.fluid.FluidPneumaticCraft@6804f045={100=Reika.RotaryCraft.Auxiliary.RecipeManagers.RecipesDryingBed$DryingRecipe@725f230d}, biomesoplenty.common.fluids.HoneyFluid@3e1d590e={400=Reika.RotaryCraft.Auxiliary.RecipeManagers.RecipesDryingBed$DryingRecipe@75ff144e}, Reika.DragonAPI.Instantiable.EnhancedFluid@3e298aaa={2000=Reika.RotaryCraft.Auxiliary.RecipeManagers.RecipesDryingBed$DryingRecipe@6a7e59e1}, net.minecraftforge.fluids.Fluid@1cfa29dd={200=Reika.RotaryCraft.Auxiliary.RecipeManagers.RecipesDryingBed$DryingRecipe@51bddfc2}, net.minecraftforge.fluids.FluidRegistry$1@22da2fe6={250=Reika.RotaryCraft.Auxiliary.RecipeManagers.RecipesDryingBed$DryingRecipe@5a71c9b3}, net.minecraftforge.fluids.FluidRegistry$2@11787b64={1000=Reika.RotaryCraft.Auxiliary.RecipeManagers.RecipesDryingBed$DryingRecipe@5721fbd7}, net.minecraftforge.fluids.Fluid@507e5e01={400=Reika.RotaryCraft.Auxiliary.RecipeManagers.RecipesDryingBed$DryingRecipe@4f081183}}Report this to Reika!
	at Reika.RotaryCraft.Auxiliary.RecipeManagers.RecipesDryingBed.getRecipe(RecipesDryingBed.java:119)
	at Reika.RotaryCraft.ModInterface.NEI.DryingBedHandler.loadCraftingRecipes(DryingBedHandler.java:122)
	at codechicken.nei.recipe.TemplateRecipeHandler.loadCraftingRecipes(TemplateRecipeHandler.java:331)
	at Reika.RotaryCraft.ModInterface.NEI.DryingBedHandler.loadCraftingRecipes(DryingBedHandler.java:109)
	at codechicken.nei.recipe.TemplateRecipeHandler.getRecipeHandler(TemplateRecipeHandler.java:466)
	at codechicken.nei.recipe.GuiCraftingRecipe.openRecipeGui(GuiCraftingRecipe.java:20)
	at codechicken.nei.ItemPanel.mouseUp(ItemPanel.java:258)
	at codechicken.nei.LayoutManager.onMouseUp(LayoutManager.java:166)
	at codechicken.nei.guihook.GuiContainerManager.mouseUp(GuiContainerManager.java:365)
	at codechicken.nei.guihook.GuiContainerManager.overrideMouseUp(GuiContainerManager.java:357)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

i already tried this https://github.com/Beyond-Reality/Beyond-Reality-Divergence/issues/106  but it didn't help

**Comment by MineMaarten** [comment]
Duplicate with https://github.com/MineMaarten/PneumaticCraft/issues/675

**Comment by Joshi120** [comment]
so uhm is there a solution for this :) ?
