### ISSUE TITLE
Etching Acid Icon missing

### ISSUE THREAD

**Issue by JasonMcRay** [MineMaarten/PneumaticCraft#824]
When PcCraft Etchind Acid is added as a fluid in recipes (for example with GregTech Fluid Canner) the icon is the Missing Icon texture. I talked to Blood Asp (current maintainer of GT5) he said that it needs to be added on PcCraft side, and he can do nothing about that.

Here is a scresshot. bucket is Etching Acid Bucket. Fluid Canner is able to "remove the fluid from containers". But as you can see on the right the etching acid fluid itself is missing texture.
![2016-02-23_20 18 09](https://cloud.githubusercontent.com/assets/4236895/13263658/c9f7482e-da6a-11e5-8699-659256c6dc90.png)

Same goes for when adding the Etching Acid into HQM as a consume task (to consume the Fluid itself through QDS)
![2016-02-23_20 22 00](https://cloud.githubusercontent.com/assets/4236895/13263725/22548c98-da6b-11e5-8dc2-b54e2336b181.png)

Tested with 1.12.6-149

**Comment by MineMaarten** [comment]
This isn't an issue anymore in the MC1.8 version of the mod. Also, this bug is too minor to be fixed in MC1.7 still. sorry.

**Comment by LachimHeigrim** [comment]
@MineMaarten unfortunately this might be more serious. I got 100% reproducible crash in 1.7.10 when placing a bucket of etching acid to the Mariculture vat. 

```java
[23:51:16] [Client thread/FATAL]: Unreported exception thrown!
java.lang.NullPointerException
	at mariculture.core.render.RenderBase.renderFluid(RenderBase.java:184) ~[RenderBase.class:?]
	at mariculture.core.render.RenderVat.renderBlock(RenderVat.java:36) ~[RenderVat.class:?]
	at mariculture.core.render.RenderBase.render(RenderBase.java:66) ~[RenderBase.class:?]
	at mariculture.core.render.RenderBase.render(RenderBase.java:45) ~[RenderBase.class:?]
	at mariculture.core.render.RenderHandler.renderWorldBlock(RenderHandler.java:33) ~[RenderHandler.class:?]
	at cpw.mods.fml.client.registry.RenderingRegistry.renderWorldBlock(RenderingRegistry.java:118) ~[RenderingRegistry.class:?]
	at FMLRenderAccessLibrary.renderWorldBlock(FMLRenderAccessLibrary.java:53) ~[FMLRenderAccessLibrary.class:?]
	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:296) ~[blm.class:?]
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:181) ~[blo.class:?]
	at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:1530) ~[bma.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1187) ~[blt.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1015) ~[blt.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?] 
`
