### ISSUE TITLE
Stall on disperseAir

### ISSUE THREAD

**Issue by TATDK** [MineMaarten/PneumaticCraft#825]
```
Stall report from 2016-02-24 13:48:03, 55 threads, stalled for at least 30000 ms.
 
"Server thread" #41 prio=5
RUNNABLE
    at pneumaticCraft.common.tileentity.TileEntityPneumaticBase.disperseAir(TileEntityPneumaticBase.java:161)
    at pneumaticCraft.common.tileentity.TileEntityPneumaticBase.disperseAir(TileEntityPneumaticBase.java:103)
    at pneumaticCraft.common.tileentity.TileEntityPneumaticBase.func_145845_h(TileEntityPneumaticBase.java:93)
    at pneumaticCraft.common.tileentity.TileEntityPressureTube.func_145845_h(TileEntityPressureTube.java:116)
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

**Comment by MineMaarten** [comment]
As the relevant code is years old at this point, do you know how I can reproduce this? Possibly even a world copy?

**Comment by CandiceJoy** [comment]
World save here: https://www.dropbox.com/s/9az1tm3lepg0b15/world.zip?dl=0

The pack is For the Love of Adventure on Curse, latest release version.

**Comment by tomato3017** [comment]
Having the same issue as above

**Comment by Fayti1703** [comment]
Do you have large pressure systems (as in, with a lot of components, even if it's just a long tubeline somewhere)? It seems to get stuck on dividing the air equally.

**Comment by tomato3017** [comment]
Yes, I noticed that it decreased alot when I moved the main compressor closer and cut out the main line.

**Comment by tomato3017** [comment]
So I posted this to the modpack author as well in case it was a mod interaction(unlikely). Below is a copy of my data I posted to https://www.reddit.com/r/Technode/comments/488qs2/anyone_else_crashing_alot/.

Ok, Here you go
Just the world https://dl.dropboxusercontent.com/u/2851909/debug/world.zip
Full snapshot(pruned) in case you need it(153mb) https://dl.dropboxusercontent.com/u/2851909/debug/fullserversnapshot-pruned.zip
Images
http://imgur.com/a/pP9Kw 
Coords x z y -292 -12569 149
Luckily I logged my time before I started testing it again. So I pulled my snapshot right before the crash. To replicate, just turn on the compressor and the refinery(Lever above compressed iron). It will still happen when one or the other is off but with both on it seems to happen quicker.
Let me know if you need anything else. I'll post this to the repo as well.
