### ISSUE TITLE
Lord of the Rings Mod Compatability

### ISSUE THREAD

**Issue by DocGandalf** [MineMaarten/PneumaticCraft#856]
LotR is just what it sounds like, it is a mod that adds everything you could want from middle-earth, however, I really like this mod too. When I was exploring Middle-Earth with some of my friends on a private server we attacked a pack of orcs and it didn't exactly crash the game, but it immediately forced us to disconnect from the server. We could reconnect and sometimes it would let us stay and fight the orcs, and sometimes it would disconnect us. I know that pneumatic craft is indeed the culprit, because I looked through the log and found one of the numerous times the server disconnected me. Here is a section of it: 
[13:40:35] [Client thread/ERROR] [FML/]: SimpleChannelHandlerWrapper exception

java.lang.ClassCastException: net.minecraft.client.entity.EntityClientPlayerMP cannot be cast to net.minecraft.entity.player.EntityPlayerMP

	at lotr.common.entity.npc.LOTRSpeech.sendSpeech(LOTRSpeech.java:206) ~[LOTRSpeech.class:?]

	at lotr.common.entity.npc.LOTREntityNPC.sendSpeechBank(LOTREntityNPC.java:1675) ~[LOTREntityNPC.class:?]

	at lotr.common.entity.npc.LOTREntityNPC.sendSpeechBank(LOTREntityNPC.java:1650) ~[LOTREntityNPC.class:?]

	at lotr.common.entity.npc.LOTREntityNPC.func_70624_b(LOTREntityNPC.java:416) ~[LOTREntityNPC.class:?]

	at pneumaticCraft.common.network.PacketSetMobTarget.handleClientSide(PacketSetMobTarget.java:36) ~[PacketSetMobTarget.class:?]

	at pneumaticCraft.common.network.PacketSetMobTarget.handleClientSide(PacketSetMobTarget.java:9) ~[PacketSetMobTarget.class:?]

	at pneumaticCraft.common.network.AbstractPacket.onMessage(AbstractPacket.java:17) ~[AbstractPacket.class:?]

	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37)

When I removed pneumaticCraft and tried it again, it was flawless. I have also posted this to LOTR.

**Comment by Fayti1703** [comment]
I see nothing wrong on PneumaticCraft's part, though don't take this as anything other than a guess.
